export const sociosAdapter = {
  adaptarPayload1: (data) => {
    if (!data) return data;
    return {
      SocioID: data?.socioID ?? data?.SocioID,
      EntidadID: data?.entidadID ?? data?.EntidadID,
      TipoSocioID: data?.tipoSocioID ?? data?.TipoSocioID,
      Cuit: data?.cuit ?? data?.Cuit,
      Denominacion: data?.denominacion ?? data?.Denominacion,
      Calle: data?.calle ?? data?.Calle,
      Numero: data?.numero ?? data?.Numero,
      Piso: data?.piso ?? data?.Piso,
      Departamento: data?.departamento ?? data?.Departamento,
      CiudadID: data?.ciudadID ?? data?.CiudadID,
      Telefono: data?.telefono ?? data?.Telefono,
      Fax: data?.fax ?? data?.Fax,
      Email: data?.email ?? data?.Email,
      TipoPersonaID: data?.tipoPersonaID ?? data?.TipoPersonaID,
      TipoCarteraID: data?.tipoCarteraID ?? data?.TipoCarteraID,
      SectorContableID: data?.sectorContableID ?? data?.SectorContableID,
      TipoActividadBCRAID: data?.tipoActividadBCRAID ?? data?.TipoActividadBCRAID,
      TipoActividadSEPYMEID: data?.tipoActividadSEPYMEID ?? data?.TipoActividadSEPYMEID,
      MarcaVinculacion: data?.marcaVinculacion ?? data?.MarcaVinculacion,
      SituacionBCRAID: data?.situacionBCRAID ?? data?.SituacionBCRAID,
      FechaBaja: data?.fechaBaja ?? data?.FechaBaja,
      MotivoBajaID: data?.motivoBajaID ?? data?.MotivoBajaID,
      SocioEstadoId: data?.socioEstadoId ?? data?.SocioEstadoId,
      CodPos: data?.codPos ?? data?.CodPos,
      TamanioEmpresaId: data?.tamanioEmpresaId ?? data?.TamanioEmpresaId,
      FechaCierreEjercicio: data?.fechaCierreEjercicio ?? data?.FechaCierreEjercicio,
      Legajo: data?.legajo ?? data?.Legajo,
      TipoRegimenIvaId: data?.tipoRegimenIvaId ?? data?.TipoRegimenIvaId,
      ActividadEspecifica: data?.actividadEspecifica ?? data?.ActividadEspecifica,
      Partido: data?.partido ?? data?.Partido,
      Telefono2: data?.telefono2 ?? data?.Telefono2,
      Telefono3: data?.telefono3 ?? data?.Telefono3,
      Visitado: data?.visitado ?? data?.Visitado,
      ScoringComercial: data?.scoringComercial ?? data?.ScoringComercial,
      PartidoId: data?.partidoId ?? data?.PartidoId,
      FechaInicioActividades: data?.fechaInicioActividades ?? data?.FechaInicioActividades,
      TipoActividadGlobalId: data?.tipoActividadGlobalId ?? data?.TipoActividadGlobalId,
      TipoCanalComercializacionID: data?.tipoCanalComercializacionID ?? data?.TipoCanalComercializacionID,
      EmailFacturacion: data?.emailFacturacion ?? data?.EmailFacturacion,
      MinApoderadosRequeridos: data?.minApoderadosRequeridos ?? data?.MinApoderadosRequeridos,
      TipoCondicionFianzaID: data?.tipoCondicionFianzaID ?? data?.TipoCondicionFianzaID,
      JsonCondicionFianza: data?.jsonCondicionFianza ?? data?.JsonCondicionFianza,
    };
  },
  adaptarPayload2: (data) => {
    if (!data) return data;
    return {
      SocioID: data?.socioID ?? data?.SocioID,
      EntidadID: data?.entidadID ?? data?.EntidadID,
      TipoSocioID: data?.tipoSocioID ?? data?.TipoSocioID,
      Cuit: data?.cuit ?? data?.Cuit,
      Denominacion: data?.denominacion ?? data?.Denominacion,
      Calle: data?.calle ?? data?.Calle,
      Numero: data?.numero ?? data?.Numero,
      Piso: data?.piso ?? data?.Piso,
      Departamento: data?.departamento ?? data?.Departamento,
      CiudadID: data?.ciudadID ?? data?.CiudadID,
      Telefono: data?.telefono ?? data?.Telefono,
      Fax: data?.fax ?? data?.Fax,
      Email: data?.email ?? data?.Email,
      TipoPersonaID: data?.tipoPersonaID ?? data?.TipoPersonaID,
      TipoCarteraID: data?.tipoCarteraID ?? data?.TipoCarteraID,
      SectorContableID: data?.sectorContableID ?? data?.SectorContableID,
      TipoActividadBCRAID: data?.tipoActividadBCRAID ?? data?.TipoActividadBCRAID,
      TipoActividadSEPYMEID: data?.tipoActividadSEPYMEID ?? data?.TipoActividadSEPYMEID,
      MarcaVinculacion: data?.marcaVinculacion ?? data?.MarcaVinculacion,
      SituacionBCRAID: data?.situacionBCRAID ?? data?.SituacionBCRAID,
      FechaBaja: data?.fechaBaja ?? data?.FechaBaja,
      MotivoBajaID: data?.motivoBajaID ?? data?.MotivoBajaID,
      SocioEstadoId: data?.socioEstadoId ?? data?.SocioEstadoId,
      CodPos: data?.codPos ?? data?.CodPos,
      TamanioEmpresaId: data?.tamanioEmpresaId ?? data?.TamanioEmpresaId,
      FechaCierreEjercicio: data?.fechaCierreEjercicio ?? data?.FechaCierreEjercicio,
      Legajo: data?.legajo ?? data?.Legajo,
      TipoRegimenIvaId: data?.tipoRegimenIvaId ?? data?.TipoRegimenIvaId,
      ActividadEspecifica: data?.actividadEspecifica ?? data?.ActividadEspecifica,
      Partido: data?.partido ?? data?.Partido,
      Telefono2: data?.telefono2 ?? data?.Telefono2,
      Telefono3: data?.telefono3 ?? data?.Telefono3,
      Visitado: data?.visitado ?? data?.Visitado,
      ScoringComercial: data?.scoringComercial ?? data?.ScoringComercial,
      PartidoId: data?.partidoId ?? data?.PartidoId,
      FechaInicioActividades: data?.fechaInicioActividades ?? data?.FechaInicioActividades,
      TipoActividadGlobalId: data?.tipoActividadGlobalId ?? data?.TipoActividadGlobalId,
      TipoCanalComercializacionID: data?.tipoCanalComercializacionID ?? data?.TipoCanalComercializacionID,
      EmailFacturacion: data?.emailFacturacion ?? data?.EmailFacturacion,
      MinApoderadosRequeridos: data?.minApoderadosRequeridos ?? data?.MinApoderadosRequeridos,
      TipoCondicionFianzaID: data?.tipoCondicionFianzaID ?? data?.TipoCondicionFianzaID,
      JsonCondicionFianza: data?.jsonCondicionFianza ?? data?.JsonCondicionFianza,
    };
  },
  adaptarPayload3: (data) => {
    if (!data) return data;
    return {
      UsuarioWebID: data?.usuarioWebID ?? data?.UsuarioWebID,
      SocioID: data?.socioID ?? data?.SocioID,
      momentoCreacion: data?.momentoCreacion ?? data?.momentoCreacion,
    };
  },
};
